FROM 10.110.18.200:9222/basic/jre:1.8
MAINTAINER  www.aurine.cn
ENV TZ=Asia/Shanghai
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /opt
ADD ./target/cert-adown-biz.jar ./
EXPOSE 6060
CMD java -Xms128m -Xmx512m -Djava.security.egd=file:/dev/./urandom  -jar cert-adown-biz.jar --spring.profiles.active=pre